#!/usr/bin/env bash
set -euo pipefail

# Resolve repo root based on this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR" && pwd)"

# If the script is inside tools/scripts/etc, adjust:
# REPO_ROOT should be the directory that contains package.json (common case)
if [ -f "$REPO_ROOT/package.json" ]; then
  :
else
  # Walk up until we find package.json; stop at filesystem root
  while [ "$REPO_ROOT" != "/" ] && [ ! -f "$REPO_ROOT/package.json" ]; do
    REPO_ROOT="$(dirname "$REPO_ROOT")"
  done
fi

LOG_DIR="$REPO_ROOT/logs"
mkdir -p "$LOG_DIR"

# Write env file usable by Node/TS apps
ENV_FILE="$REPO_ROOT/.env.local"
cat > "$ENV_FILE" <<EOF
# generated by set-logger-path.sh
LOG_DIR=$LOG_DIR
EOF

echo "Wrote LOG_DIR=$LOG_DIR to $ENV_FILE"
echo "Created directory: $LOG_DIR"
