export const runtime = 'nodejs'
// Diagnostics + self-repair endpoint
// Checks ~/ai-helper/ structure and reports what's missing
import { NextResponse } from 'next/server'
import { stat, mkdir, writeFile } from 'fs/promises'
import { homedir } from 'os'
import path from 'path'

const REQUIRED_DIRS = [
  'ai-helper',
  'ai-helper/scripts',
  'ai-helper/logs',
  'ai-helper/tmp',
  'ai-helper/logs/archive',
]

const REQUIRED_SCRIPTS = [
  'boot_dispatcher.sh',
  'maintenance_daily.sh',
  'watchdog_lite.sh',
  'shizuku_runner.sh',
]

interface CheckResult {
  path: string
  type: 'dir' | 'file'
  exists: boolean
  repaired?: boolean
}

export async function GET() {
  const home = homedir()
  const results: CheckResult[] = []

  // Check directories
  for (const dir of REQUIRED_DIRS) {
    const fullPath = path.join(home, dir)
    try {
      await stat(fullPath)
      results.push({ path: fullPath, type: 'dir', exists: true })
    } catch {
      results.push({ path: fullPath, type: 'dir', exists: false })
    }
  }

  // Check scripts
  for (const script of REQUIRED_SCRIPTS) {
    const fullPath = path.join(home, 'ai-helper', 'scripts', script)
    try {
      await stat(fullPath)
      results.push({ path: fullPath, type: 'file', exists: true })
    } catch {
      results.push({ path: fullPath, type: 'file', exists: false })
    }
  }

  const healthy = results.every(r => r.exists)
  return NextResponse.json({ healthy, checks: results })
}

export async function POST() {
  // Self-repair: create missing dirs, stub missing scripts
  const home = homedir()
  const repaired: string[] = []
  const failed: string[] = []

  // Repair directories
  for (const dir of REQUIRED_DIRS) {
    const fullPath = path.join(home, dir)
    try {
      await mkdir(fullPath, { recursive: true })
      repaired.push(fullPath)
    } catch {
      failed.push(fullPath)
    }
  }

  // Stub missing scripts
  for (const script of REQUIRED_SCRIPTS) {
    const fullPath = path.join(home, 'ai-helper', 'scripts', script)
    try {
      await stat(fullPath)
    } catch {
      try {
        const stub = `#!/bin/bash
# AI Helper stub: ${script}
# Generated by diagnostics self-repair on ${new Date().toISOString()}
# Edit this file to add your real automation logic.

ACTION="\${1:-run}"
LOG_DIR="\${HOME}/ai-helper/logs"
TMP_DIR="\${HOME}/ai-helper/tmp"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] ${script} started — action: \${ACTION}"
echo "STUB: Replace this with real commands for ${script}"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] ${script} complete"
`
        await writeFile(fullPath, stub, { mode: 0o755 })
        repaired.push(fullPath)
      } catch {
        failed.push(fullPath)
      }
    }
  }

  return NextResponse.json({
    ok: failed.length === 0,
    repaired,
    failed,
    message: failed.length === 0
      ? 'All missing items repaired successfully'
      : `${repaired.length} repaired, ${failed.length} failed`,
  })
}
