#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# AI Helper — One-Time Setup Script
# Run this ONCE on your Chromebook Linux terminal to initialize
# the ~/ai-helper/ directory structure and install all scripts.
#
# Usage: bash public/scripts/setup.sh
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
HOME_DIR="${HOME}"
AI_DIR="${HOME_DIR}/ai-helper"
SCRIPTS_DIR="${AI_DIR}/scripts"
LOGS_DIR="${AI_DIR}/logs"
TMP_DIR="${AI_DIR}/tmp"
ARCHIVE_DIR="${LOGS_DIR}/archive"

# Script source dir (where this setup.sh lives, relative to project root)
SCRIPT_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║          AI HELPER — SETUP INITIALIZER              ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "[${TIMESTAMP}] Starting setup..."
echo ""

# ── 1. Create directory structure ────────────────────────────
echo "► Creating directory structure..."
mkdir -p "${SCRIPTS_DIR}" "${LOGS_DIR}" "${TMP_DIR}" "${ARCHIVE_DIR}"
echo "  ✓ ${AI_DIR}/"
echo "  ✓ ${SCRIPTS_DIR}/"
echo "  ✓ ${LOGS_DIR}/"
echo "  ✓ ${TMP_DIR}/"

# ── 2. Copy scripts ───────────────────────────────────────────
echo ""
echo "► Installing scripts to ${SCRIPTS_DIR}/"
SCRIPTS=("boot_dispatcher.sh" "maintenance_daily.sh" "watchdog_lite.sh" "shizuku_runner.sh")
for script in "${SCRIPTS[@]}"; do
  SRC="${SCRIPT_SRC}/${script}"
  DEST="${SCRIPTS_DIR}/${script}"
  if [ -f "${SRC}" ]; then
    cp "${SRC}" "${DEST}"
    chmod +x "${DEST}"
    echo "  ✓ ${script}"
  else
    echo "  ✗ ${script} not found at ${SRC} — creating stub"
    cat > "${DEST}" <<STUB
#!/bin/bash
# AI Helper stub: ${script}
# Generated by setup.sh on ${TIMESTAMP}
# Replace with your real automation logic.
echo "[$(date '+%Y-%m-%d %H:%M:%S')] ${script} stub — action: \${1:-run}"
echo "STUB_OK"
STUB
    chmod +x "${DEST}"
  fi
done

# ── 3. Write default config ────────────────────────────────────
echo ""
echo "► Writing default config..."
CONFIG_FILE="${AI_DIR}/config.json"
if [ ! -f "${CONFIG_FILE}" ]; then
  cat > "${CONFIG_FILE}" <<EOF
{
  "destructive_mode": "B",
  "watchdog_interval_minutes": 15,
  "daily_maintenance_hour": 3,
  "max_log_entries": 100,
  "ai_helper_port": 13000,
  "timeout_multiplier": 1.0,
  "setup_complete": true,
  "last_updated": "${TIMESTAMP}"
}
EOF
  echo "  ✓ config.json written"
else
  echo "  ↺ config.json already exists — preserving"
fi

# ── 4. Install crontab entries ────────────────────────────────
echo ""
echo "► Installing cron jobs..."

CRON_DAILY="0 3 * * * bash ${SCRIPTS_DIR}/maintenance_daily.sh >> ${LOGS_DIR}/maintenance.log 2>&1"
CRON_WATCHDOG="*/15 * * * * bash ${SCRIPTS_DIR}/watchdog_lite.sh >> ${LOGS_DIR}/watchdog.log 2>&1"

# Get existing crontab (ignore errors if empty)
EXISTING_CRON=$(crontab -l 2>/dev/null || echo "")

UPDATED_CRON="${EXISTING_CRON}"

if ! echo "${EXISTING_CRON}" | grep -q "maintenance_daily.sh"; then
  UPDATED_CRON="${UPDATED_CRON}
${CRON_DAILY}"
  echo "  ✓ Daily maintenance cron added (0 3 * * *)"
else
  echo "  ↺ Daily maintenance cron already exists"
fi

if ! echo "${EXISTING_CRON}" | grep -q "watchdog_lite.sh"; then
  UPDATED_CRON="${UPDATED_CRON}
${CRON_WATCHDOG}"
  echo "  ✓ Watchdog cron added (*/15 * * * *)"
else
  echo "  ↺ Watchdog cron already exists"
fi

echo "${UPDATED_CRON}" | crontab - 2>/dev/null || echo "  ⚠ Could not update crontab — add manually"

# ── 5. Check for adb ─────────────────────────────────────────
echo ""
echo "► Checking for ADB..."
if which adb &>/dev/null; then
  ADB_VER=$(adb version | head -1)
  echo "  ✓ ADB found: ${ADB_VER}"
else
  echo "  ⚠ ADB not found. Install with:"
  echo "    sudo apt-get update && sudo apt-get install -y adb"
fi

# ── 6. systemd service (optional) ────────────────────────────
echo ""
echo "► systemd auto-start setup..."
SYSTEMD_DIR="${HOME_DIR}/.config/systemd/user"
SERVICE_SRC="$(cd "${SCRIPT_SRC}/../.." && pwd)/systemd/ai-helper.service"

if [ -f "${SERVICE_SRC}" ]; then
  mkdir -p "${SYSTEMD_DIR}"
  echo "  To enable auto-start at Linux boot, run:"
  echo "    cp ${SERVICE_SRC} ${SYSTEMD_DIR}/"
  echo "    systemctl --user enable ai-helper.service"
  echo "    systemctl --user start ai-helper.service"
else
  echo "  ⚠ systemd/ai-helper.service not found — skip auto-start setup"
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║                  SETUP COMPLETE                     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  AI Helper is ready. Start the app:"
echo "    pnpm start"
echo ""
echo "  Then open: http://localhost:13000"
echo ""
